printWidth: 80 # 每行代码的最大宽度
tabWidth: 2 # 每个缩进级别的空格数
useTabs: false # 使用空格而不是制表符进行缩进
semi: true # 在语句末尾添加分号
singleQuote: true # 使用单引号而不是双引号
quoteProps: as-needed # 仅在需要时在对象属性周围添加引号
jsxSingleQuote: false # 在 JSX 中使用双引号
trailingComma: es5 # 在 ES5 中有效的尾随逗号（对象、数组等）
bracketSpacing: true # 在对象字面量的括号之间打印空格
jsxBracketSameLine: false # 将 JSX 的闭合标签放在最后一行的末尾
arrowParens: always # 在箭头函数参数周围始终添加括号
proseWrap: preserve # 保留 Markdown 文本的换行
htmlWhitespaceSensitivity: css # 根据 CSS 样式处理 HTML 空白字符
endOfLine: lf # 使用 LF 作为行尾符
embeddedLanguageFormatting: auto # 自动格式化嵌入的代码（如 Markdown 中的代码块）
